/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kuisonline.view.siswa;

import kuisonline.MainFrame;
import kuisonline.model.Kuis;
import kuisonline.model.Pengguna;

/**
 *
 * @author TUF GAMING
 */
public class DashboardSiswa extends javax.swing.JPanel {

    private Pengguna userLogged;

    private MainFrame mainFrame;
    private Dashboard dashboard = new Dashboard(this);
    private KuisDetail kuisDetail = new KuisDetail(this);
    private JawabKuis jawabKuis = new JawabKuis(this);

    private java.awt.CardLayout cardLayout = new java.awt.CardLayout();

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardSiswa(MainFrame mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        MainContent.setLayout(cardLayout);
        MainContent.add(dashboard, "Dashboard");
        MainContent.add(kuisDetail, "KuisDetail");
        MainContent.add(jawabKuis, "JawabKuis");

    }

    public void setUser(Pengguna userLogged) {
        this.userLogged = userLogged;

        hellotext.setText("Halo " + userLogged.getName() + "!");
    }
    
    public Pengguna getUser() {
        return userLogged;
    }

    public void dashboard() {
        cardLayout.show(MainContent, "Dashboard");
        dashboard.refreshKuisPanel();
    }

    public void kuisDetail(Kuis kuis) {
        cardLayout.show(MainContent, "KuisDetail");
        kuisDetail.setKuisDetail(kuis);
    }

    public void jawabKuis(Kuis kuis) {
        cardLayout.show(MainContent, "JawabKuis");
        jawabKuis.setKuis(kuis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBar = new javax.swing.JPanel();
        hellotext = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        MenuItem = new javax.swing.JPanel();
        MenuItem_Dashboard = new javax.swing.JPanel();
        DashboardText = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        TambahSoalText1 = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        TopBar.setBackground(new java.awt.Color(36, 37, 42));
        TopBar.setPreferredSize(new java.awt.Dimension(800, 32));
        TopBar.setLayout(new java.awt.CardLayout());

        hellotext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hellotext.setForeground(new java.awt.Color(255, 255, 255));
        hellotext.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hellotext.setText("Halo, siswa!");
        TopBar.add(hellotext, "card2");

        add(TopBar, java.awt.BorderLayout.PAGE_START);

        SideBar.setBackground(new java.awt.Color(55, 58, 73));
        SideBar.setPreferredSize(new java.awt.Dimension(60, 480));
        SideBar.setLayout(new java.awt.BorderLayout());

        MenuItem.setLayout(new java.awt.GridLayout(0, 1));

        MenuItem_Dashboard.setBackground(new java.awt.Color(55, 58, 73));
        MenuItem_Dashboard.setPreferredSize(new java.awt.Dimension(100, 60));
        MenuItem_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_DashboardMouseClicked(evt);
            }
        });
        MenuItem_Dashboard.setLayout(new java.awt.CardLayout(10, 10));

        DashboardText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/home.png"))); // NOI18N
        DashboardText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_Dashboard.add(DashboardText, "card2");

        MenuItem.add(MenuItem_Dashboard);

        SideBar.add(MenuItem, java.awt.BorderLayout.PAGE_START);

        Logout.setBackground(new java.awt.Color(55, 58, 73));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new java.awt.CardLayout(10, 10));

        TambahSoalText1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahSoalText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/logout.png"))); // NOI18N
        TambahSoalText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.add(TambahSoalText1, "card2");

        SideBar.add(Logout, java.awt.BorderLayout.PAGE_END);

        add(SideBar, java.awt.BorderLayout.WEST);

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setPreferredSize(new java.awt.Dimension(640, 468));
        MainContent.setLayout(new java.awt.CardLayout());
        add(MainContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_DashboardMouseClicked
        dashboard();
    }//GEN-LAST:event_MenuItem_DashboardMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        this.userLogged = null;

        mainFrame.login();
    }//GEN-LAST:event_LogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashboardText;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel MenuItem;
    private javax.swing.JPanel MenuItem_Dashboard;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel TambahSoalText1;
    private javax.swing.JPanel TopBar;
    private javax.swing.JLabel hellotext;
    // End of variables declaration//GEN-END:variables
}
