/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kuisonline.view.siswa;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import kuisonline.controller.HasilKuisDAO;
import kuisonline.controller.KuisDAO;
import kuisonline.model.HasilKuis;
import kuisonline.model.Kuis;
import kuisonline.model.Pertanyaan;

/**
 *
 * @author TUF GAMING
 */
public class JawabKuis extends javax.swing.JPanel {

    private DashboardSiswa mainPanel;

    private Kuis kuis;
    private Pertanyaan pertanyaan;
    private int nomorsoal = 1;
    private Timer timer;
    private int hitungMundur;
    
    private int terjawabBenar = 0;

    /**
     * Creates new form JawabKuis
     */
    public JawabKuis(DashboardSiswa mainPanel) {
        this.mainPanel = mainPanel;

        initComponents();
    }

    void setKuis(Kuis kuis) {
        this.kuis = kuis;
        mainPanel.toggleSidebar();
        
        nomorsoal = 1;
        terjawabBenar = 0;
        setPertanyaan();
    }

    void setPertanyaan() {
        pertanyaan = kuis.getPertanyaan().get(nomorsoal - 1);

        this.removeAll();
        initComponents();
        this.revalidate();
        this.repaint();
        
        if(kuis.getJumlahPertanyaan() == nomorsoal) {
            next.setText("Selesai");
        }

        nomor.setText(nomorsoal + "");
        soal.setText(pertanyaan.getTeksPertanyaan());
        jawabana.setText(pertanyaan.getJawabanA());
        jawabanb.setText(pertanyaan.getJawabanB());
        jawabanc.setText(pertanyaan.getJawabanC());
        jawaband.setText(pertanyaan.getJawabanD());
        jawabane.setText(pertanyaan.getJawabanE());

        if (kuis.getWaktuPengerjaan() > 0) {
            setWaktu();
        } else {
            waktusoal.setForeground(new Color(240, 240, 240));
        }
    }

    void setWaktu() {
        hitungMundur = kuis.getWaktuPengerjaan();
        waktusoal.setMaximum(hitungMundur);

        timer = new Timer(1000, new ActionListener() { // 1000 ms = 1 detik
            @Override
            public void actionPerformed(ActionEvent e) {
                hitungMundur--; // Kurangi waktu
                waktusoal.setValue(hitungMundur); // Perbarui progress bar
                waktusoal.setString(+hitungMundur + "d");

                if (hitungMundur <= 0) {
                    timer.stop(); // Hentikan timer
                    simpanJawaban();
                }
            }
        });

        timer.start(); // Mulai timer
    }

    void simpanJawaban() {
        String jawabanBenar = pertanyaan.getJawabanBenar();
        String jawabanDipilih = "";

        if (pilihana.isSelected()) {
            jawabanDipilih = "a";
        }
        if (pilihanb.isSelected()) {
            jawabanDipilih = "b";
        }
        if (pilihanc.isSelected()) {
            jawabanDipilih = "c";
        }
        if (pilihand.isSelected()) {
            jawabanDipilih = "d";
        }
        if (pilihane.isSelected()) {
            jawabanDipilih = "e";
        }
        
        if(jawabanDipilih.equalsIgnoreCase(jawabanBenar)) {
            terjawabBenar++;
        }
        
        if(kuis.getJumlahPertanyaan() == nomorsoal) {
            // Simpan Ke Database
            HasilKuis hasil = new HasilKuis();
            hasil.setIdKuis(kuis.getIdKuis());
            hasil.setIdPengguna(mainPanel.getUser().getIdPengguna());
            hasil.setTotalBenar(terjawabBenar);
            
            try {
                HasilKuisDAO.addKuis(hasil);
                
                kuis = KuisDAO.getKuisById(kuis.getIdKuis());
            } catch (SQLException ex) {
                Logger.getLogger(JawabKuis.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            mainPanel.kuisDetail(kuis);
            mainPanel.toggleSidebar();
        } else {
            // Soal Selanjutnya
            nomorsoal++;
            
            setPertanyaan();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihan = new javax.swing.ButtonGroup();
        waktusoal = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        jPanel15 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pilihana = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jawabana = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        pilihanb = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jawabanb = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        pilihanc = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jawabanc = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        pilihand = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jawaband = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        pilihane = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jawabane = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        nomor = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        waktusoal.setValue(100);
        waktusoal.setString("");
        waktusoal.setStringPainted(true);
        add(waktusoal, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setLayout(new java.awt.CardLayout(10, 10));

        soal.setEditable(false);
        soal.setColumns(20);
        soal.setLineWrap(true);
        soal.setRows(5);
        soal.setText("Soal");
        soal.setBorder(null);
        jScrollPane1.setViewportView(soal);

        jPanel4.add(jScrollPane1, "card2");

        jPanel2.add(jPanel4);

        jPanel15.setLayout(new java.awt.GridLayout(3, 0));

        jPanel6.setLayout(new java.awt.CardLayout(10, 10));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        pilihan.add(pilihana);
        jPanel5.add(pilihana);

        jawabana.setEditable(false);
        jawabana.setColumns(20);
        jawabana.setLineWrap(true);
        jawabana.setRows(5);
        jawabana.setText("Jawaban A");
        jawabana.setBorder(null);
        jScrollPane2.setViewportView(jawabana);

        jPanel5.add(jScrollPane2);

        jPanel6.add(jPanel5, "card2");

        jPanel15.add(jPanel6);

        jPanel7.setLayout(new java.awt.CardLayout(10, 10));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        pilihan.add(pilihanb);
        jPanel8.add(pilihanb);

        jawabanb.setEditable(false);
        jawabanb.setColumns(20);
        jawabanb.setLineWrap(true);
        jawabanb.setRows(5);
        jawabanb.setText("Jawaban B");
        jawabanb.setBorder(null);
        jScrollPane3.setViewportView(jawabanb);

        jPanel8.add(jScrollPane3);

        jPanel7.add(jPanel8, "card2");

        jPanel15.add(jPanel7);

        jPanel9.setLayout(new java.awt.CardLayout(10, 10));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.LINE_AXIS));

        pilihan.add(pilihanc);
        jPanel10.add(pilihanc);

        jawabanc.setEditable(false);
        jawabanc.setColumns(20);
        jawabanc.setLineWrap(true);
        jawabanc.setRows(5);
        jawabanc.setText("Jawaban C");
        jawabanc.setBorder(null);
        jScrollPane4.setViewportView(jawabanc);

        jPanel10.add(jScrollPane4);

        jPanel9.add(jPanel10, "card2");

        jPanel15.add(jPanel9);

        jPanel11.setLayout(new java.awt.CardLayout(10, 10));

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        pilihan.add(pilihand);
        jPanel12.add(pilihand);

        jawaband.setEditable(false);
        jawaband.setColumns(20);
        jawaband.setLineWrap(true);
        jawaband.setRows(5);
        jawaband.setText("Jawaban D");
        jawaband.setBorder(null);
        jScrollPane5.setViewportView(jawaband);

        jPanel12.add(jScrollPane5);

        jPanel11.add(jPanel12, "card2");

        jPanel15.add(jPanel11);

        jPanel13.setLayout(new java.awt.CardLayout(10, 10));

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        pilihan.add(pilihane);
        jPanel14.add(pilihane);

        jawabane.setEditable(false);
        jawabane.setColumns(20);
        jawabane.setLineWrap(true);
        jawabane.setRows(5);
        jawabane.setText("Jawaban E");
        jawabane.setBorder(null);
        jScrollPane6.setViewportView(jawabane);

        jPanel14.add(jScrollPane6);

        jPanel13.add(jPanel14, "card2");

        jPanel15.add(jPanel13);

        jPanel2.add(jPanel15);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        next.setText("Selanjutnya");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel3.add(next, java.awt.BorderLayout.LINE_END);

        nomor.setText("Nomor Soal");
        jPanel3.add(nomor, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        timer.stop();
        simpanJawaban();
    }//GEN-LAST:event_nextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jawabana;
    private javax.swing.JTextArea jawabanb;
    private javax.swing.JTextArea jawabanc;
    private javax.swing.JTextArea jawaband;
    private javax.swing.JTextArea jawabane;
    private javax.swing.JButton next;
    private javax.swing.JLabel nomor;
    private javax.swing.ButtonGroup pilihan;
    private javax.swing.JRadioButton pilihana;
    private javax.swing.JRadioButton pilihanb;
    private javax.swing.JRadioButton pilihanc;
    private javax.swing.JRadioButton pilihand;
    private javax.swing.JRadioButton pilihane;
    private javax.swing.JTextArea soal;
    private javax.swing.JProgressBar waktusoal;
    // End of variables declaration//GEN-END:variables
}
