/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kuisonline.view.siswa;

import java.sql.SQLException;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import kuisonline.controller.HasilKuisDAO;
import kuisonline.model.HasilKuis;
import kuisonline.model.Kuis;

/**
 *
 * @author TUF GAMING
 */
public class KuisDetail extends javax.swing.JPanel {

    private Kuis kuis;
    private HasilKuis hasilKuis;

    private DashboardSiswa mainPanel;

    /**
     * Creates new form KuisDetail
     */
    public KuisDetail(DashboardSiswa mainPanel) {
        this.mainPanel = mainPanel;

        initComponents();
    }

    void setKuisDetail(Kuis kuis) {
        this.kuis = kuis;

        judulKuis.setText(kuis.getJudul());
        jumlahSoal.setText(kuis.getJumlahPertanyaan() + " Soal");
        
        if(cekNilai()) {
            waktu.setText(hasilKuis.getTotalBenar() + "/" + kuis.getJumlahPertanyaan());
            mulai.setEnabled(false);
        } else {
            waktu.setText(kuis.getWaktuPengerjaan() + " Detik/Soal");
        }
    }
    
    boolean cekNilai() {
        try {
            hasilKuis = HasilKuisDAO.getHasilKuisByPengguna(kuis.getIdKuis(), mainPanel.getUser().getIdPengguna());
        } catch (SQLException ex) {
            Logger.getLogger(KuisDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return (hasilKuis != null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header_BuatSoal = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Detail = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jumlahSoal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        judulKuis = new javax.swing.JLabel();
        mulai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        Header_BuatSoal.setBackground(new java.awt.Color(255, 255, 255));
        Header_BuatSoal.setPreferredSize(new java.awt.Dimension(640, 50));
        Header_BuatSoal.setLayout(new java.awt.BorderLayout());

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        Header_BuatSoal.add(back, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.CardLayout(14, 6));
        Header_BuatSoal.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(Header_BuatSoal, java.awt.BorderLayout.PAGE_START);

        Detail.setLayout(new java.awt.GridLayout(0, 1));
        Detail.add(jPanel6);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jumlahSoal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahSoal.setText("10 Soal");
        jPanel2.add(jumlahSoal);

        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setText("30 Detik/Soal (Jadi Skor Kalau Sudah Selesai)");
        jPanel2.add(waktu);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        judulKuis.setBackground(new java.awt.Color(255, 255, 255));
        judulKuis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulKuis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulKuis.setText("Judul Kuis");
        jPanel1.add(judulKuis, java.awt.BorderLayout.PAGE_START);

        mulai.setText("Mulai");
        mulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiActionPerformed(evt);
            }
        });
        jPanel1.add(mulai, java.awt.BorderLayout.PAGE_END);

        Detail.add(jPanel1);
        Detail.add(jPanel3);
        Detail.add(jPanel5);

        add(Detail, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        mainPanel.dashboard();
    }//GEN-LAST:event_backActionPerformed

    private void mulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiActionPerformed
        Kuis kuisDiAcak = kuis;
        Collections.shuffle(kuisDiAcak.getPertanyaan());
        mainPanel.jawabKuis(kuisDiAcak);
    }//GEN-LAST:event_mulaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Detail;
    private javax.swing.JPanel Header_BuatSoal;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel judulKuis;
    private javax.swing.JLabel jumlahSoal;
    private javax.swing.JButton mulai;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
