/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuisonline;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TUF GAMING
 */
public class DashboardAdmin extends javax.swing.JFrame {

    Kuis kuis;
    Pertanyaan pertanyaan[];
    DefaultTableModel model;

    private Connection conn;

    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin(String name) {
        conn = Koneksi.getConnection();

        initComponents();
        refreshTableDaftarSoal();
        hellotext.setText("Halo, " + name + "!");

        try {
            String query = "SELECT * FROM kategori";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Input_KategoriKuis.addItem(rs.getString("nama_kategori"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void refreshTableDaftarSoal() {
        model = new DefaultTableModel(new Object[]{"No", "Pertanyaan", "Jawaban Benar", "ID", "A", "B", "C", "D", "E"}, 0);

        tabelDaftarSoal.setModel(model);
        model.getDataVector().removeAllElements();

        if (kuis != null) {
            for (int i = 0; i < kuis.jumPertanyaan; i++) {
                Object[] data = {
                    i + 1,
                    pertanyaan[i].pertanyaan,
                    pertanyaan[i].jawabanbenar,
                    pertanyaan[i].idPertanyaan,
                    pertanyaan[i].jawabanA,
                    pertanyaan[i].jawabanB,
                    pertanyaan[i].jawabanC,
                    pertanyaan[i].jawabanD,
                    pertanyaan[i].jawabanE,};
                model.addRow(data);
            }
        }

        for (int i = 3; i <= 8; i++) {
            tabelDaftarSoal.getColumnModel().getColumn(i).setMinWidth(0);
            tabelDaftarSoal.getColumnModel().getColumn(i).setMaxWidth(0);
            tabelDaftarSoal.getColumnModel().getColumn(i).setWidth(0);
        }
    }

    //Edit container daftar soal
//    void editSoalContainer(int jumlahSoal) {
//        DaftarSoal.setPreferredSize(new Dimension(DaftarSoal.getWidth(), 50*jumlahSoal));
//        
//        //Buat Container Dari Masing-masing soal
//        ArrayList<javax.swing.JPanel> listsoal = new ArrayList<javax.swing.JPanel>();
//        
//        for(int i = 0; i < jumlahSoal; i++) {
//            listsoal.add(new javax.swing.JPanel());
//            listsoal.get(i).setBorder(javax.swing.BorderFactory.createEtchedBorder());
//            listsoal.get(i).setPreferredSize(new java.awt.Dimension(680, 40));
//            listsoal.get(i).setLayout(new java.awt.BorderLayout());
//
//            DaftarSoal.add(listsoal.get(i));
//        }
//        
//        ArrayList<javax.swing.JLabel> textpertanyaan = new ArrayList<javax.swing.JLabel>();
//        ArrayList<javax.swing.JButton> btnedit = new ArrayList<javax.swing.JButton>();
//        
//        for(int i = 0; i < jumlahSoal; i++) {
//            
//            textpertanyaan.add(new javax.swing.JLabel());
//            textpertanyaan.get(i).setText("apalah" + (i+1));
//            
//            btnedit.add(new javax.swing.JButton());
//            btnedit.get(i).setBackground(new java.awt.Color(255, 153, 0));
//            btnedit.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/edit.png"))); // NOI18N
//
//            listsoal.get(i).add(btnedit.get(i), java.awt.BorderLayout.LINE_END);
//            listsoal.get(i).add(textpertanyaan.get(i), java.awt.BorderLayout.CENTER);
//        }
//        
//        jScrollPane1.revalidate();
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jawabanbenar = new javax.swing.ButtonGroup();
        TopBar = new javax.swing.JPanel();
        hellotext = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        MenuItem = new javax.swing.JPanel();
        MenuItem_Dashboard = new javax.swing.JPanel();
        DashboardText = new javax.swing.JLabel();
        MenuItem_TambahSoal = new javax.swing.JPanel();
        TambahSoalText = new javax.swing.JLabel();
        MainContent_SemuaMapel = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Card = new javax.swing.JPanel();
        CardGrid = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        MainContent_Kuis = new javax.swing.JPanel();
        Header_BuatSoal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        FormKuis = new javax.swing.JPanel();
        Form1 = new javax.swing.JPanel();
        Form3 = new javax.swing.JPanel();
        JudulSoal2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        Input_JudulKuis = new javax.swing.JTextField();
        InputGroup2 = new javax.swing.JPanel();
        KategoriSoal1 = new javax.swing.JPanel();
        Input_KategoriKuis = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        WaktuPengerjaan1 = new javax.swing.JPanel();
        Input_JumlahSoal = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        WaktuPengerjaan2 = new javax.swing.JPanel();
        Input_WaktuPengerjaan = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarSoal = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        simpankuis = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        input_pertanyaan = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        abenar = new javax.swing.JRadioButton();
        input_jawabana = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        bbenar = new javax.swing.JRadioButton();
        input_jawabanb = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        cbenar = new javax.swing.JRadioButton();
        input_jawabanc = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        dbenar = new javax.swing.JRadioButton();
        input_jawaband = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        ebenar = new javax.swing.JRadioButton();
        input_jawabane = new javax.swing.JTextField();
        simpan_soal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        TopBar.setBackground(new java.awt.Color(36, 37, 42));
        TopBar.setPreferredSize(new java.awt.Dimension(800, 32));
        TopBar.setLayout(new java.awt.CardLayout());

        hellotext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hellotext.setForeground(new java.awt.Color(255, 255, 255));
        hellotext.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hellotext.setText("Halo, admin!");
        TopBar.add(hellotext, "card2");

        getContentPane().add(TopBar, java.awt.BorderLayout.PAGE_START);

        SideBar.setBackground(new java.awt.Color(55, 58, 73));
        SideBar.setPreferredSize(new java.awt.Dimension(60, 480));
        SideBar.setLayout(new java.awt.BorderLayout());

        MenuItem.setLayout(new java.awt.GridLayout(0, 1));

        MenuItem_Dashboard.setBackground(new java.awt.Color(55, 58, 73));
        MenuItem_Dashboard.setPreferredSize(new java.awt.Dimension(100, 60));
        MenuItem_Dashboard.setLayout(new java.awt.CardLayout(10, 10));

        DashboardText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/home.png"))); // NOI18N
        DashboardText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_Dashboard.add(DashboardText, "card2");

        MenuItem.add(MenuItem_Dashboard);

        MenuItem_TambahSoal.setBackground(new java.awt.Color(55, 58, 73));
        MenuItem_TambahSoal.setPreferredSize(new java.awt.Dimension(100, 40));
        MenuItem_TambahSoal.setLayout(new java.awt.CardLayout(10, 10));

        TambahSoalText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahSoalText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/add_post.png"))); // NOI18N
        TambahSoalText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_TambahSoal.add(TambahSoalText, "card2");

        MenuItem.add(MenuItem_TambahSoal);

        SideBar.add(MenuItem, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(SideBar, java.awt.BorderLayout.WEST);

        MainContent_SemuaMapel.setBackground(new java.awt.Color(255, 255, 255));
        MainContent_SemuaMapel.setPreferredSize(new java.awt.Dimension(640, 468));
        MainContent_SemuaMapel.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(640, 50));
        Header.setLayout(new java.awt.CardLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Semua Mapel");
        Header.add(jLabel1, "card2");

        MainContent_SemuaMapel.add(Header, java.awt.BorderLayout.PAGE_START);

        Card.setBackground(new java.awt.Color(255, 255, 255));
        Card.setPreferredSize(new java.awt.Dimension(640, 140));
        Card.setLayout(new java.awt.CardLayout());

        CardGrid.setBackground(new java.awt.Color(255, 255, 255));
        CardGrid.setPreferredSize(new java.awt.Dimension(700, 140));
        CardGrid.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        jPanel2.setBackground(new java.awt.Color(251, 251, 251));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel2.setLayout(new java.awt.CardLayout(20, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bahasa Indonesia");
        jPanel2.add(jLabel2, "card2");

        CardGrid.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(251, 251, 251));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel3.setLayout(new java.awt.CardLayout(20, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Matematika");
        jPanel3.add(jLabel3, "card2");

        CardGrid.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(251, 251, 251));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel4.setLayout(new java.awt.CardLayout(20, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("IPA");
        jPanel4.add(jLabel4, "card2");

        CardGrid.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(251, 251, 251));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel6.setLayout(new java.awt.CardLayout(20, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("IPS");
        jPanel6.add(jLabel5, "card2");

        CardGrid.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(251, 251, 251));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel7.setLayout(new java.awt.CardLayout(20, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bahasa Java");
        jPanel7.add(jLabel6, "card2");

        CardGrid.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(251, 251, 251));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 60));
        jPanel8.setLayout(new java.awt.CardLayout(20, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bahasa PHP");
        jPanel8.add(jLabel7, "card2");

        CardGrid.add(jPanel8);

        Card.add(CardGrid, "card2");

        MainContent_SemuaMapel.add(Card, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainContent_SemuaMapel, java.awt.BorderLayout.CENTER);

        MainContent_Kuis.setBackground(new java.awt.Color(255, 255, 255));
        MainContent_Kuis.setPreferredSize(new java.awt.Dimension(640, 468));
        MainContent_Kuis.setLayout(new java.awt.BorderLayout());

        Header_BuatSoal.setBackground(new java.awt.Color(255, 255, 255));
        Header_BuatSoal.setPreferredSize(new java.awt.Dimension(640, 50));
        Header_BuatSoal.setLayout(new java.awt.CardLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Buat Kuis");
        Header_BuatSoal.add(jLabel8, "card2");

        MainContent_Kuis.add(Header_BuatSoal, java.awt.BorderLayout.PAGE_START);

        FormKuis.setBackground(new java.awt.Color(255, 255, 255));
        FormKuis.setPreferredSize(new java.awt.Dimension(740, 140));
        FormKuis.setLayout(new java.awt.CardLayout(10, 10));

        Form1.setBackground(new java.awt.Color(255, 255, 255));
        Form1.setLayout(new java.awt.BorderLayout());

        Form3.setBackground(new java.awt.Color(255, 255, 255));
        Form3.setLayout(new java.awt.GridLayout(2, 1, 0, 8));

        JudulSoal2.setBackground(new java.awt.Color(255, 255, 255));
        JudulSoal2.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("Judul Kuis");
        JudulSoal2.add(jLabel15, java.awt.BorderLayout.PAGE_START);

        Input_JudulKuis.setText("Judul Kuis");
        Input_JudulKuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_JudulKuisActionPerformed(evt);
            }
        });
        JudulSoal2.add(Input_JudulKuis, java.awt.BorderLayout.CENTER);

        Form3.add(JudulSoal2);

        InputGroup2.setBackground(new java.awt.Color(255, 255, 255));
        InputGroup2.setLayout(new java.awt.GridLayout(1, 0, 6, 0));

        KategoriSoal1.setBackground(new java.awt.Color(255, 255, 255));
        KategoriSoal1.setLayout(new java.awt.BorderLayout());

        Input_KategoriKuis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori" }));
        Input_KategoriKuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input_KategoriKuisActionPerformed(evt);
            }
        });
        KategoriSoal1.add(Input_KategoriKuis, java.awt.BorderLayout.CENTER);

        jLabel16.setText("Kategori Kuis");
        KategoriSoal1.add(jLabel16, java.awt.BorderLayout.PAGE_START);

        InputGroup2.add(KategoriSoal1);

        WaktuPengerjaan1.setBackground(new java.awt.Color(255, 255, 255));
        WaktuPengerjaan1.setLayout(new java.awt.BorderLayout());

        Input_JumlahSoal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Input_JumlahSoalFocusGained(evt);
            }
        });
        WaktuPengerjaan1.add(Input_JumlahSoal, java.awt.BorderLayout.CENTER);

        jLabel19.setText("Jumlah Soal");
        WaktuPengerjaan1.add(jLabel19, java.awt.BorderLayout.PAGE_START);

        InputGroup2.add(WaktuPengerjaan1);

        WaktuPengerjaan2.setBackground(new java.awt.Color(255, 255, 255));
        WaktuPengerjaan2.setLayout(new java.awt.BorderLayout());
        WaktuPengerjaan2.add(Input_WaktuPengerjaan, java.awt.BorderLayout.CENTER);

        jLabel18.setText("Waktu Pengerjaan (Menit)");
        WaktuPengerjaan2.add(jLabel18, java.awt.BorderLayout.PAGE_START);

        InputGroup2.add(WaktuPengerjaan2);

        Form3.add(InputGroup2);

        Form1.add(Form3, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(null);

        tabelDaftarSoal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDaftarSoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDaftarSoalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDaftarSoal);

        Form1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        simpankuis.setText("Simpan");
        simpankuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpankuisActionPerformed(evt);
            }
        });
        jPanel9.add(simpankuis, java.awt.BorderLayout.LINE_END);

        jPanel5.add(jPanel9);

        Form1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        input_pertanyaan.setColumns(20);
        input_pertanyaan.setRows(5);
        jScrollPane2.setViewportView(input_pertanyaan);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel17.setText("Pertanyaan");
        jPanel13.add(jLabel17, java.awt.BorderLayout.PAGE_START);

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        jPanel22.setLayout(new java.awt.BorderLayout());

        abenar.setBackground(new java.awt.Color(255, 255, 255));
        jawabanbenar.add(abenar);
        abenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abenarActionPerformed(evt);
            }
        });
        jPanel22.add(abenar, java.awt.BorderLayout.LINE_START);

        input_jawabana.setText("jTextField1");
        jPanel22.add(input_jawabana, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel22);

        jPanel18.setLayout(new java.awt.BorderLayout());

        bbenar.setBackground(new java.awt.Color(255, 255, 255));
        jawabanbenar.add(bbenar);
        bbenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbenarActionPerformed(evt);
            }
        });
        jPanel18.add(bbenar, java.awt.BorderLayout.LINE_START);

        input_jawabanb.setText("jTextField1");
        jPanel18.add(input_jawabanb, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        cbenar.setBackground(new java.awt.Color(255, 255, 255));
        jawabanbenar.add(cbenar);
        cbenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbenarActionPerformed(evt);
            }
        });
        jPanel19.add(cbenar, java.awt.BorderLayout.LINE_START);

        input_jawabanc.setText("jTextField1");
        jPanel19.add(input_jawabanc, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());

        dbenar.setBackground(new java.awt.Color(255, 255, 255));
        jawabanbenar.add(dbenar);
        dbenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbenarActionPerformed(evt);
            }
        });
        jPanel20.add(dbenar, java.awt.BorderLayout.LINE_START);

        input_jawaband.setText("jTextField1");
        jPanel20.add(input_jawaband, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel20);

        jPanel21.setLayout(new java.awt.BorderLayout());

        ebenar.setBackground(new java.awt.Color(255, 255, 255));
        jawabanbenar.add(ebenar);
        ebenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebenarActionPerformed(evt);
            }
        });
        jPanel21.add(ebenar, java.awt.BorderLayout.LINE_START);

        input_jawabane.setText("jTextField1");
        jPanel21.add(input_jawabane, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel21);

        simpan_soal.setText("Simpan Soal");
        simpan_soal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_soalActionPerformed(evt);
            }
        });
        jPanel14.add(simpan_soal);

        jPanel12.add(jPanel14, java.awt.BorderLayout.CENTER);

        Form1.add(jPanel12, java.awt.BorderLayout.LINE_START);

        FormKuis.add(Form1, "card2");

        MainContent_Kuis.add(FormKuis, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainContent_Kuis, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Input_JudulKuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_JudulKuisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_JudulKuisActionPerformed

    private void Input_KategoriKuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_KategoriKuisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_KategoriKuisActionPerformed

    private void simpankuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpankuisActionPerformed
        Boolean dibuat = false;

        String judulkuis = Input_JudulKuis.getText();
        int kategorikuis = Input_KategoriKuis.getSelectedIndex();
        int waktupengerjaan = (int) Input_WaktuPengerjaan.getValue();

        if (!dibuat) {
            int jumlahsoal = (int) Input_JumlahSoal.getValue();
            kuis = new Kuis(0, judulkuis, jumlahsoal, waktupengerjaan, kategorikuis);
            pertanyaan = kuis.buatPertanyaan();
            Input_JumlahSoal.setEnabled(false);
            dibuat = true;

            // Simpan data kuis
            try {
                String query;
                PreparedStatement pst;

                query = "INSERT INTO kuis (judul, jumlah_pertanyaan, waktu_pengerjaan, id_kategori) values (?, ?, ?, ?)";
                pst = conn.prepareStatement(query);

                pst.setString(1, kuis.judul);
                pst.setInt(2, kuis.jumPertanyaan);
                pst.setInt(3, kuis.waktuPengerjaan);
                pst.setInt(4, kuis.kategori);

                pst.executeUpdate();
                pst = conn.prepareStatement("SELECT id_kuis FROM kuis ORDER BY id_kuis DESC LIMIT 1;");
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    kuis.idKuis = rs.getInt(1);
                }

                for (int i = 0; i < pertanyaan.length; i++) {
                    query = "INSERT INTO pertanyaan (teks_pertanyaan, jawabanA, jawabanB, jawabanC, jawabanD, jawabanE, jawaban_benar, id_kuis) values (?, ?, ?, ?, ?, ?, ?, ?)";
                    pst = conn.prepareStatement(query);

                    pst.setString(1, pertanyaan[i].pertanyaan);
                    pst.setString(2, pertanyaan[i].jawabanA);
                    pst.setString(3, pertanyaan[i].jawabanB);
                    pst.setString(4, pertanyaan[i].jawabanC);
                    pst.setString(5, pertanyaan[i].jawabanD);
                    pst.setString(6, pertanyaan[i].jawabanE);
                    pst.setString(7, pertanyaan[i].jawabanbenar);
                    pst.setInt(8, kuis.idKuis);

                    pst.executeUpdate();

                    pst = conn.prepareStatement("SELECT id_pertanyaan FROM pertanyaan ORDER BY id_pertanyaan DESC LIMIT 1;");
                    rs = pst.executeQuery();
                    while (rs.next()) {
                        pertanyaan[i].idPertanyaan = rs.getInt(1);
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        refreshTableDaftarSoal();
    }//GEN-LAST:event_simpankuisActionPerformed

    private void Input_JumlahSoalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Input_JumlahSoalFocusGained
//        int input = Integetr.parseInt( Input_JumlahSoal.getValue().toString());
//        if(input == 0) {
//            Input_JumlahSoal.setValue(Integer.toString());
//        } 
    }//GEN-LAST:event_Input_JumlahSoalFocusGained

    private void bbenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bbenarActionPerformed

    private void cbenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbenarActionPerformed

    private void dbenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dbenarActionPerformed

    private void ebenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebenarActionPerformed

    private void tabelDaftarSoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDaftarSoalMouseClicked
        int selectedRow = tabelDaftarSoal.getSelectedRow();

        if (selectedRow != -1) { // artinya jika ada data yang diklik
            String pertanyaan = tabelDaftarSoal.getValueAt(selectedRow, 1).toString();
            String jawabanbenar = tabelDaftarSoal.getValueAt(selectedRow, 2).toString();
            int id = Integer.parseInt(tabelDaftarSoal.getValueAt(selectedRow, 3).toString());
            String jawabana = tabelDaftarSoal.getValueAt(selectedRow, 4).toString();
            String jawabanb = tabelDaftarSoal.getValueAt(selectedRow, 5).toString();
            String jawabanc = tabelDaftarSoal.getValueAt(selectedRow, 6).toString();
            String jawaband = tabelDaftarSoal.getValueAt(selectedRow, 7).toString();
            String jawabane = tabelDaftarSoal.getValueAt(selectedRow, 8).toString();

            input_pertanyaan.setText(pertanyaan);
            input_jawabana.setText(jawabana);
            input_jawabanb.setText(jawabanb);
            input_jawabanc.setText(jawabanc);
            input_jawaband.setText(jawaband);
            input_jawabane.setText(jawabane);

            switch (jawabanbenar) {
                case "a":
                    abenar.setSelected(true);
                    break;
                case "b":
                    bbenar.setSelected(true);
                    break;
                case "c":
                    cbenar.setSelected(true);
                    break;
                case "d":
                    dbenar.setSelected(true);
                    break;
                case "e":
                    ebenar.setSelected(true);
                    break;
            }
        }
    }//GEN-LAST:event_tabelDaftarSoalMouseClicked

    private void abenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abenarActionPerformed

    private void simpan_soalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_soalActionPerformed
        int selectedRow = tabelDaftarSoal.getSelectedRow();
        String jawabanbenar = "";
        
        int index = Integer.parseInt(tabelDaftarSoal.getValueAt(selectedRow, 0).toString()) -1;

        if (selectedRow == -1) { // artinya jika tidak ada tabel yang diklik
            JOptionPane.showMessageDialog(null, "Select row first!", "validasi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(abenar.isSelected()) jawabanbenar = "a";
        if(bbenar.isSelected()) jawabanbenar = "b";
        if(cbenar.isSelected()) jawabanbenar = "c";
        if(dbenar.isSelected()) jawabanbenar = "d";
        if(ebenar.isSelected()) jawabanbenar = "e";
        
        try {
            String query = "UPDATE pertanyaan SET teks_pertanyaan = ?, jawabanA = ?, jawabanB = ?, jawabanC = ?, jawabanD = ?, jawabanE = ?, jawaban_benar = ? WHERE id_pertanyaan = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, input_pertanyaan.getText());
            pst.setString(2, input_jawabana.getText());
            pst.setString(3, input_jawabanb.getText());
            pst.setString(4, input_jawabanc.getText());
            pst.setString(5, input_jawaband.getText());
            pst.setString(6, input_jawabane.getText());
            pst.setString(7, jawabanbenar);
            pst.setInt(8, pertanyaan[index].idPertanyaan);
            
            int rowUpdate = pst.executeUpdate();
                if(rowUpdate > 0) {
                    JOptionPane.showMessageDialog(null,"Update data successfull!");
                    
                    pertanyaan[index].pertanyaan = input_pertanyaan.getText();
                    pertanyaan[index].jawabanA = input_jawabana.getText();
                    pertanyaan[index].jawabanB = input_jawabanb.getText();
                    pertanyaan[index].jawabanC = input_jawabanc.getText();
                    pertanyaan[index].jawabanD = input_jawaband.getText();
                    pertanyaan[index].jawabanE = input_jawabane.getText();
                    pertanyaan[index].jawabanbenar = jawabanbenar;
                    
                    refreshTableDaftarSoal();
                }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_simpan_soalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstateFormBuatlapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stayFormBuat the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Card;
    private javax.swing.JPanel CardGrid;
    private javax.swing.JLabel DashboardText;
    private javax.swing.JPanel Form1;
    private javax.swing.JPanel Form3;
    private javax.swing.JPanel FormKuis;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header_BuatSoal;
    private javax.swing.JPanel InputGroup2;
    private javax.swing.JTextField Input_JudulKuis;
    private javax.swing.JSpinner Input_JumlahSoal;
    private javax.swing.JComboBox<String> Input_KategoriKuis;
    private javax.swing.JSpinner Input_WaktuPengerjaan;
    private javax.swing.JPanel JudulSoal2;
    private javax.swing.JPanel KategoriSoal1;
    private javax.swing.JPanel MainContent_Kuis;
    private javax.swing.JPanel MainContent_SemuaMapel;
    private javax.swing.JPanel MenuItem;
    private javax.swing.JPanel MenuItem_Dashboard;
    private javax.swing.JPanel MenuItem_TambahSoal;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel TambahSoalText;
    private javax.swing.JPanel TopBar;
    private javax.swing.JPanel WaktuPengerjaan1;
    private javax.swing.JPanel WaktuPengerjaan2;
    private javax.swing.JRadioButton abenar;
    private javax.swing.JRadioButton bbenar;
    private javax.swing.JRadioButton cbenar;
    private javax.swing.JRadioButton dbenar;
    private javax.swing.JRadioButton ebenar;
    private javax.swing.JLabel hellotext;
    private javax.swing.JTextField input_jawabana;
    private javax.swing.JTextField input_jawabanb;
    private javax.swing.JTextField input_jawabanc;
    private javax.swing.JTextField input_jawaband;
    private javax.swing.JTextField input_jawabane;
    private javax.swing.JTextArea input_pertanyaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jawabanbenar;
    private javax.swing.JButton simpan_soal;
    private javax.swing.JButton simpankuis;
    private javax.swing.JTable tabelDaftarSoal;
    // End of variables declaration//GEN-END:variables
}
