/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuisonline.view.admin;

import kuisonline.model.Kuis;
import kuisonline.model.Pengguna;

/**
 *
 * @author TUF GAMING
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private Pengguna userLogged;

    private java.awt.CardLayout cardLayout = new java.awt.CardLayout();
    private Dashboard dashboard = new Dashboard(this);
    private BuatKuis buatKuis = new BuatKuis();
    private KuisDetail kuisDetail = new KuisDetail(this);
    private EditKuis editKuis = new EditKuis(this);
    ;
    /**
     * Creates new form Dashboard
     */
    public DashboardAdmin(Pengguna userLogged) {
        this.userLogged = userLogged;
        
        initComponents();

        MainContent.setLayout(cardLayout);
        MainContent.add(dashboard, "Dashboard");
        MainContent.add(buatKuis, "BuatKuis");
        MainContent.add(kuisDetail, "KuisDetail");
        MainContent.add(editKuis, "EditKuis");
    }
    
    public void dashboard() {
        cardLayout.show(MainContent, "Dashboard");
        dashboard.refreshKuisPanel();
    }

    public void buatKuis() {
        cardLayout.show(MainContent, "BuatKuis");
        buatKuis.reset();
    }

    public void kuisDetail(Kuis kuis) {
        cardLayout.show(MainContent, "KuisDetail");
        kuisDetail.setKuisDetail(kuis);
    }

    public void editKuis(Kuis kuis) {
        cardLayout.show(MainContent, "EditKuis");
        editKuis.setKuis(kuis);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jawabanbenar = new javax.swing.ButtonGroup();
        TopBar = new javax.swing.JPanel();
        hellotext = new javax.swing.JLabel();
        SideBar = new javax.swing.JPanel();
        MenuItem = new javax.swing.JPanel();
        MenuItem_Dashboard = new javax.swing.JPanel();
        DashboardText = new javax.swing.JLabel();
        MenuItem_TambahSoal = new javax.swing.JPanel();
        TambahSoalText = new javax.swing.JLabel();
        MainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        TopBar.setBackground(new java.awt.Color(36, 37, 42));
        TopBar.setPreferredSize(new java.awt.Dimension(800, 32));
        TopBar.setLayout(new java.awt.CardLayout());

        hellotext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        hellotext.setForeground(new java.awt.Color(255, 255, 255));
        hellotext.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        hellotext.setText("Halo, admin!");
        TopBar.add(hellotext, "card2");

        getContentPane().add(TopBar, java.awt.BorderLayout.PAGE_START);

        SideBar.setBackground(new java.awt.Color(55, 58, 73));
        SideBar.setPreferredSize(new java.awt.Dimension(60, 480));
        SideBar.setLayout(new java.awt.BorderLayout());

        MenuItem.setLayout(new java.awt.GridLayout(0, 1));

        MenuItem_Dashboard.setBackground(new java.awt.Color(55, 58, 73));
        MenuItem_Dashboard.setPreferredSize(new java.awt.Dimension(100, 60));
        MenuItem_Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_DashboardMouseClicked(evt);
            }
        });
        MenuItem_Dashboard.setLayout(new java.awt.CardLayout(10, 10));

        DashboardText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/home.png"))); // NOI18N
        DashboardText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_Dashboard.add(DashboardText, "card2");

        MenuItem.add(MenuItem_Dashboard);

        MenuItem_TambahSoal.setBackground(new java.awt.Color(55, 58, 73));
        MenuItem_TambahSoal.setPreferredSize(new java.awt.Dimension(100, 40));
        MenuItem_TambahSoal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItem_TambahSoalMouseClicked(evt);
            }
        });
        MenuItem_TambahSoal.setLayout(new java.awt.CardLayout(10, 10));

        TambahSoalText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TambahSoalText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuisonline/assets/add_post.png"))); // NOI18N
        TambahSoalText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuItem_TambahSoal.add(TambahSoalText, "card2");

        MenuItem.add(MenuItem_TambahSoal);

        SideBar.add(MenuItem, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(SideBar, java.awt.BorderLayout.WEST);

        MainContent.setBackground(new java.awt.Color(255, 255, 255));
        MainContent.setPreferredSize(new java.awt.Dimension(640, 468));
        MainContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(MainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem_DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_DashboardMouseClicked
        dashboard();
    }//GEN-LAST:event_MenuItem_DashboardMouseClicked

    private void MenuItem_TambahSoalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItem_TambahSoalMouseClicked
        buatKuis();
    }//GEN-LAST:event_MenuItem_TambahSoalMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashboardText;
    private javax.swing.JPanel MainContent;
    private javax.swing.JPanel MenuItem;
    private javax.swing.JPanel MenuItem_Dashboard;
    private javax.swing.JPanel MenuItem_TambahSoal;
    private javax.swing.JPanel SideBar;
    private javax.swing.JLabel TambahSoalText;
    private javax.swing.JPanel TopBar;
    private javax.swing.JLabel hellotext;
    private javax.swing.ButtonGroup jawabanbenar;
    // End of variables declaration//GEN-END:variables
}
