/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package kuisonline.view.admin;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kuisonline.controller.KuisDAO;
import kuisonline.model.Kuis;

/**
 *
 * @author TUF GAMING
 */
public class KuisDetail extends javax.swing.JPanel {

    private Kuis kuis;

    private DashboardAdmin mainFrame;

    /**
     * Creates new form KuisDetail
     */
    public KuisDetail(DashboardAdmin mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();
    }

    void setKuisDetail(Kuis kuis) {
        this.kuis = kuis;

        judulKuis.setText(kuis.getJudul());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header_BuatSoal = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        judulKuis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Header_BuatSoal.setBackground(new java.awt.Color(255, 255, 255));
        Header_BuatSoal.setPreferredSize(new java.awt.Dimension(640, 50));
        Header_BuatSoal.setLayout(new java.awt.BorderLayout());

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        Header_BuatSoal.add(back, java.awt.BorderLayout.LINE_START);

        jPanel4.setLayout(new java.awt.CardLayout(14, 6));

        judulKuis.setBackground(new java.awt.Color(255, 255, 255));
        judulKuis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulKuis.setText("Judul Kuis");
        jPanel4.add(judulKuis, "card2");

        Header_BuatSoal.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(Header_BuatSoal, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(jPanel3);

        edit.setText("Edit Kuis");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);

        hapus.setText("Hapus Kuis");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        mainFrame.editKuis(kuis);
    }//GEN-LAST:event_editActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        mainFrame.dashboard();
    }//GEN-LAST:event_backActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int response = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin menghapus kuis ini?",
                "Konfirmasi Hapus Kuis",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            try {
                KuisDAO.deleteKuis(kuis.getIdKuis());
            } catch (SQLException ex) {
                Logger.getLogger(KuisDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            mainFrame.dashboard();
        }
    }//GEN-LAST:event_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header_BuatSoal;
    private javax.swing.JButton back;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel judulKuis;
    // End of variables declaration//GEN-END:variables
}
